apiVersion: v1
kind: ConfigMap
metadata:
  name: task-management-config
  namespace: task-management
data:
  # Non-Sensitive Configuration
  APP_NAME: "Task Management System"
  VERSION: "1.0.0"
  ENVIRONMENT: "development"
  DEBUG: "true"
  LOG_LEVEL: "INFO"

  # Database connection (non-sensitive)
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "taskdb"

  # Redis Connection (non-sensitive)
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

  # Security Settings (non-sensitive)
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  REFRESH_TOKEN_EXPIRE_MINUTES: "10080"

  # File Upload settings
  MAX_FILE_SIZE: "10485760"
  ALLOWED_FILE_TYPES: "image/jpeg,image/png,application/pdf,text/plain"

  # AWS Setting
  AWS_REGION: "us-east-1"
  S3_BUCKET_NAME: "task-management-files"