Version: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: task-management
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 10Gi
