apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: task-management
data:
  redis.conf: |
    # Redis Configuration for Task Management System
    
    # Network
    bind 0.0.0.0
    port 6379
    
    # General
    daemonize no
    supervised no
    
    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    
    # Append only file for durability
    appendonly yes
    appendfsync everysec
    
    # Memory Management
    maxmemory 200mb
    maxmemory-policy allkeys-lru
    
    # Logging
    loglevel notice
    
    # Performance
    tcp-keepalive 300
    timeout 0