apiVersion: v1
kind: Secret
metadata:
  name: task-management-secrets
  namespace: task-management
type: Opaque
data:
  DATABASE_USER: dGFza3VzZXI=
  DATABASE_PASSWORD: UmFzaGltYW5zaHVAMTcwNw==

  SECRET_KEY: dGhpcyBpcyBqdXN0IGEgc2VjcmV0IGtleSE=

  # AWS Credentials
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
