apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-management-api-sa
  namespace: task-management

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: task-management-api-role
  namespace: task-management
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: task-management-api-binding
  namespace: task-management
subjects:
- kind: ServiceAccount
  name: task-management-api-sa
  namespace: task-management
roleRef:
  kind: Role
  name: task-management-api-role
  apiGroup: rbac.authorization.k8s.io